name: kustasoft_web_browser
#60 ile 180 arasında karakter açıklama yaz flutter web browser eklentisi
description: "A new Flutter plugin for opening web browser in Android and iOS. This plugin is based on the Flutter plugin template."
version: 0.0.3
homepage: https://github.com/kustasoft/kustasoft_web_browser
repository: https://github.com/kustasoft/kustasoft_web_browser/tree/master
issue_tracker: https://github.com/kustasoft/kustasoft_web_browser/issues

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kustasoft.kustasoft_web_browser
        pluginClass: KustasoftWebBrowserPlugin
      ios:
        pluginClass: KustasoftWebBrowserPlugin
