name: kustasoft_web_browser
description: "Flutter plugin for opening web browser"
version: 0.0.1
homepage: https://github.com/kustasoft/kustasoft_web_browser
repository: https://github.com/kustasoft/kustasoft_web_browser/tree/master
issue_tracker: https://github.com/kustasoft/kustasoft_web_browser/issues

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kustasoft.kustasoft_web_browser
        pluginClass: KustasoftWebBrowserPlugin
      ios:
        pluginClass: KustasoftWebBrowserPlugin
